pipeline {
  agent {
    docker {
      image 'node:6-alpine'
      args '-p 3000:3000'
    }

  }
  stages {
    stage('Build') {
      steps {
        sh 'npm install'
        sh 'docker stop flask'
        sh 'docker swarm leave -f'
        sh 'docker build -t macalahthomas/tcmg476:four .'
        sh 'docker swarm init'
        sh 'docker stack deploy -c docker-compose.yml flask'
      }
    }
    stage('Test') {
      environment {
        CI = 'true'
      }
      steps {
        sh 'python3 -m pip install requests'
        sh 'python3 ./test.py'
      }
    }
    stage('Deliver') {
      steps {
        sh './jenkins/scripts/deliver.sh'
        input 'Finished using the web site? (Click "Proceed" to continue)'
        sh './jenkins/scripts/kill.sh'
      }
    }
  }
}
